### ISSUE TITLE
Share an opensource QCNN for Speech Repo

### ISSUE THREAD

**Issue by huckiyang** [heba0/Sound-Classification-using-Quanvolutional-Neural-Networks#1]
Hello @heba0,

Just want to share our open-source speech commands classification work related to your nice work,

https://github.com/huckiyang/QuantumSpeech-QCNN

which provides the acoustic features preprocessing with QCNN and might also align your interests. Feel free to use the code.

The paper is accepted to IEEE International Conference on Acoustics, Speech, & Signal Processing 2021

https://arxiv.org/abs/2010.13309

Good luck with your hackathon!

**Comment by heba0** [comment]
Hi @huckiyang ,
Thanks a lot for sharing! this definitely helps .
